About
nastjademchyk/WatchCharm-team-project pull request #7
Opened 2024-06-27 13:10 UTC by Slavik756

ull request Add menu to site

2024-06-28 09:22 UTC, nastjademchyk requested changes
- В тебе в css є зайві background-image, по ТЗ мусить бути:  Зображення слід реалізувати як контентні.
Але на макеті в тебе є ще там градієнт, який мусить бути в css. 
- В мобільний версії між текстом і кнопкою мусить бути  40px, в тебе 30px. (Перевір також в планшеті і десктопі).
- Header з текстом не відцентровані в сірому квадраті, а посунуті марджином від стінки. Треба щоб воно було посередині. Так само треба перевірити в планшеті і десктопі.

2024-06-28 13:13 UTC, Slavik756 commented
готово

2024-06-29 07:00 UTC, nastjademchyk requested changes
- Для зображення (.img-about) треба додати більший радіус. В тебе зараз 30px, треба 50%. 
- В стилях є зайвий селектор без властивостей: .div-img-about

2024-06-29 17:49 UTC, nastjademchyk approved these changes

2024-06-29 17:49 UTC, merged